# TODO
- 検定を終えた画像を書き出す
- ヒストグラムを出す
- ウェルチのt検定を実装する
- タイルに分割してt検定できるようにする

In [10]:
import imageio
import numpy as np
import math

# 1ピクセルをウェルチ用の1サンプルとして、
# 32x32(=1024ピクセル)のタイルを1024サンプルとして使う
img0 = imageio.imread('./pt.exr')
img1 = imageio.imread('./bdpt.exr')
(w,h,_) = img0.shape
wt = w//32
ht = h//32
img = Image.new("L", (320, 240))
#print(img.shape)
for ty in range(wt):
    for tx in range(wt):
        xb = (tx+0)*32
        xe = (tx+1)*32
        yb = (ty+0)*32
        ye = (ty+1)*32
        t0 = img0[yb:ye,xb:xe,2].flatten()
        t1 = img1[yb:ye,xb:xe,2].flatten()
        v0 = np.var(t0,ddof=1)
        v1 = np.var(t1,ddof=1)
        m0 = np.average(t0)
        m1 = np.average(t1)
        tv = (m0-m1)/math.sqrt(v0/1024 + v1/1024)
        print(tv)



2.6143928593502603
6.222724903061048
5.206274427115185
4.318415788676399
4.847701455249317
4.832399175990453
5.033898943202718
5.278513197538029
5.112104427251128
5.258077493533369
6.03906241677402
5.947613091791826
6.917876407222434
7.053761097862003
7.536173519896624
3.713513345579267
6.75618751130128
5.016953832639776
9.70545439059075
9.514345088162129
10.878048671755977
8.030081075761393
0.7059996848865204
0.24886141555195856
0.036167260671229294
0.8164846977297056
12.237948954090273
12.831033559332626
13.070050095965058
13.716982730633205
7.616276493977208
9.046030797971403
5.735090379092896
13.065137091144946
4.85406011390777
12.000990093113641
13.437220694774808
12.579211989011494
0.030611264885673263
0.0470655253102607
0.03260416435339676
0.04306756306511036
15.24094807907849
18.01782461400935
18.331319209656666
9.049367927651923
14.552613348223105
6.121570299571667
4.594553788028977
11.956229822384053
12.175914599377688
9.838370495962195
18.806128950944736
21.185841363121003
2

In [14]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[:3,:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
